create_clock -period 5.000 [get_ports sys_clk_p]

make_diff_pair_ports sys_clk_p sys_clk_n
set_property PACKAGE_PIN AK17 [get_ports sys_clk_p]
set_property PACKAGE_PIN AK16 [get_ports sys_clk_n]
set_property IOSTANDARD LVDS [get_ports sys_clk_p]
set_property IOSTANDARD LVDS [get_ports sys_clk_n]

# keys
set_property PACKAGE_PIN Y21 [get_ports {rst_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {rst_n}]
set_property PACKAGE_PIN Y22 [get_ports {user_key}]
set_property IOSTANDARD LVCMOS18 [get_ports {user_key}]

# FMC1
set_property PACKAGE_PIN W23 [get_ports {FMC1_LPC_CLK_M2C_P[0]}]
set_property PACKAGE_PIN W24 [get_ports {FMC1_LPC_CLK_M2C_N[0]}]
set_property PACKAGE_PIN AD30 [get_ports {FMC1_LPC_CLK_M2C_P[1]}]
set_property PACKAGE_PIN AD31 [get_ports {FMC1_LPC_CLK_M2C_N[1]}]
set_property PACKAGE_PIN Y23 [get_ports {FMC1_LPC_LA_P[0]}]
set_property PACKAGE_PIN AA23 [get_ports {FMC1_LPC_LA_N[0]}]
set_property PACKAGE_PIN AA24 [get_ports {FMC1_LPC_LA_P[1]}]
set_property PACKAGE_PIN AA25 [get_ports {FMC1_LPC_LA_N[1]}]
set_property PACKAGE_PIN AD25 [get_ports {FMC1_LPC_LA_P[2]}]
set_property PACKAGE_PIN AD26 [get_ports {FMC1_LPC_LA_N[2]}]
set_property PACKAGE_PIN AC26 [get_ports {FMC1_LPC_LA_P[3]}]
set_property PACKAGE_PIN AC27 [get_ports {FMC1_LPC_LA_N[3]}]
set_property PACKAGE_PIN AB25 [get_ports {FMC1_LPC_LA_P[4]}]
set_property PACKAGE_PIN AB26 [get_ports {FMC1_LPC_LA_N[4]}]
set_property PACKAGE_PIN W28 [get_ports {FMC1_LPC_LA_P[5]}]
set_property PACKAGE_PIN Y28 [get_ports {FMC1_LPC_LA_N[5]}]
set_property PACKAGE_PIN V27 [get_ports {FMC1_LPC_LA_P[6]}]
set_property PACKAGE_PIN V28 [get_ports {FMC1_LPC_LA_N[6]}]
set_property PACKAGE_PIN AA20 [get_ports {FMC1_LPC_LA_P[7]}]
set_property PACKAGE_PIN AB20 [get_ports {FMC1_LPC_LA_N[7]}]
set_property PACKAGE_PIN AA22 [get_ports {FMC1_LPC_LA_P[8]}]
set_property PACKAGE_PIN AB22 [get_ports {FMC1_LPC_LA_N[8]}]
set_property PACKAGE_PIN W25 [get_ports {FMC1_LPC_LA_P[9]}]
set_property PACKAGE_PIN Y25 [get_ports {FMC1_LPC_LA_N[9]}]
set_property PACKAGE_PIN AA27 [get_ports {FMC1_LPC_LA_P[10]}]
set_property PACKAGE_PIN AB27 [get_ports {FMC1_LPC_LA_N[10]}]
set_property PACKAGE_PIN V29 [get_ports {FMC1_LPC_LA_P[11]}]
set_property PACKAGE_PIN W29 [get_ports {FMC1_LPC_LA_N[11]}]
set_property PACKAGE_PIN U21 [get_ports {FMC1_LPC_LA_P[12]}]
set_property PACKAGE_PIN U22 [get_ports {FMC1_LPC_LA_N[12]}]
set_property PACKAGE_PIN V26 [get_ports {FMC1_LPC_LA_P[13]}]
set_property PACKAGE_PIN W26 [get_ports {FMC1_LPC_LA_N[13]}]
set_property PACKAGE_PIN Y26 [get_ports {FMC1_LPC_LA_P[14]}]
set_property PACKAGE_PIN Y27 [get_ports {FMC1_LPC_LA_N[14]}]
set_property PACKAGE_PIN U26 [get_ports {FMC1_LPC_LA_P[15]}]
set_property PACKAGE_PIN U27 [get_ports {FMC1_LPC_LA_N[15]}]
set_property PACKAGE_PIN U24 [get_ports {FMC1_LPC_LA_P[16]}]
set_property PACKAGE_PIN U25 [get_ports {FMC1_LPC_LA_N[16]}]
set_property PACKAGE_PIN AC31 [get_ports {FMC1_LPC_LA_P[17]}]
set_property PACKAGE_PIN AC32 [get_ports {FMC1_LPC_LA_N[17]}]
set_property PACKAGE_PIN AA32 [get_ports {FMC1_LPC_LA_P[18]}]
set_property PACKAGE_PIN AB32 [get_ports {FMC1_LPC_LA_N[18]}]
set_property PACKAGE_PIN AF33 [get_ports {FMC1_LPC_LA_P[19]}]
set_property PACKAGE_PIN AG34 [get_ports {FMC1_LPC_LA_N[19]}]
set_property PACKAGE_PIN AE33 [get_ports {FMC1_LPC_LA_P[20]}]
set_property PACKAGE_PIN AF34 [get_ports {FMC1_LPC_LA_N[20]}]
set_property PACKAGE_PIN AE32 [get_ports {FMC1_LPC_LA_P[21]}]
set_property PACKAGE_PIN AF32 [get_ports {FMC1_LPC_LA_N[21]}]
set_property PACKAGE_PIN AC34 [get_ports {FMC1_LPC_LA_P[22]}]
set_property PACKAGE_PIN AD34 [get_ports {FMC1_LPC_LA_N[22]}]
set_property PACKAGE_PIN AA34 [get_ports {FMC1_LPC_LA_P[23]}]
set_property PACKAGE_PIN AB34 [get_ports {FMC1_LPC_LA_N[23]}]
set_property PACKAGE_PIN W33 [get_ports {FMC1_LPC_LA_P[24]}]
set_property PACKAGE_PIN Y33 [get_ports {FMC1_LPC_LA_N[24]}]
set_property PACKAGE_PIN Y31 [get_ports {FMC1_LPC_LA_P[25]}]
set_property PACKAGE_PIN Y32 [get_ports {FMC1_LPC_LA_N[25]}]
set_property PACKAGE_PIN AB30 [get_ports {FMC1_LPC_LA_P[26]}]
set_property PACKAGE_PIN AB31 [get_ports {FMC1_LPC_LA_N[26]}]
set_property PACKAGE_PIN AA29 [get_ports {FMC1_LPC_LA_P[27]}]
set_property PACKAGE_PIN AB29 [get_ports {FMC1_LPC_LA_N[27]}]
set_property PACKAGE_PIN U34 [get_ports {FMC1_LPC_LA_P[28]}]
set_property PACKAGE_PIN V34 [get_ports {FMC1_LPC_LA_N[28]}]
set_property PACKAGE_PIN V33 [get_ports {FMC1_LPC_LA_P[29]}]
set_property PACKAGE_PIN W34 [get_ports {FMC1_LPC_LA_N[29]}]
set_property PACKAGE_PIN W30 [get_ports {FMC1_LPC_LA_P[30]}]
set_property PACKAGE_PIN Y30 [get_ports {FMC1_LPC_LA_N[30]}]
set_property PACKAGE_PIN V31 [get_ports {FMC1_LPC_LA_P[31]}]
set_property PACKAGE_PIN W31 [get_ports {FMC1_LPC_LA_N[31]}]
set_property PACKAGE_PIN AD29 [get_ports {FMC1_LPC_LA_P[32]}]
set_property PACKAGE_PIN AE30 [get_ports {FMC1_LPC_LA_N[32]}]
set_property PACKAGE_PIN AC33 [get_ports {FMC1_LPC_LA_P[33]}]
set_property PACKAGE_PIN AD33 [get_ports {FMC1_LPC_LA_N[33]}]

# FMC2
set_property PACKAGE_PIN AG11 [get_ports {FMC2_LPC_CLK_M2C_P[0]}]
set_property PACKAGE_PIN AH11 [get_ports {FMC2_LPC_CLK_M2C_N[0]}]
set_property PACKAGE_PIN P24 [get_ports {FMC2_LPC_CLK_M2C_P[1]}]
set_property PACKAGE_PIN P25 [get_ports {FMC2_LPC_CLK_M2C_N[1]}]
set_property PACKAGE_PIN AG12 [get_ports {FMC2_LPC_LA_P[0]}]
set_property PACKAGE_PIN AH12 [get_ports {FMC2_LPC_LA_N[0]}]
set_property PACKAGE_PIN AF10 [get_ports {FMC2_LPC_LA_P[1]}]
set_property PACKAGE_PIN AG10 [get_ports {FMC2_LPC_LA_N[1]}]
set_property PACKAGE_PIN AN13 [get_ports {FMC2_LPC_LA_P[2]}]
set_property PACKAGE_PIN AP13 [get_ports {FMC2_LPC_LA_N[2]}]
set_property PACKAGE_PIN AM12 [get_ports {FMC2_LPC_LA_P[3]}]
set_property PACKAGE_PIN AN12 [get_ports {FMC2_LPC_LA_N[3]}]
set_property PACKAGE_PIN AK13 [get_ports {FMC2_LPC_LA_P[4]}]
set_property PACKAGE_PIN AL13 [get_ports {FMC2_LPC_LA_N[4]}]
set_property PACKAGE_PIN AL10 [get_ports {FMC2_LPC_LA_P[5]}]
set_property PACKAGE_PIN AM10 [get_ports {FMC2_LPC_LA_N[5]}]
set_property PACKAGE_PIN AP11 [get_ports {FMC2_LPC_LA_P[6]}]
set_property PACKAGE_PIN AP10 [get_ports {FMC2_LPC_LA_N[6]}]
set_property PACKAGE_PIN AK12 [get_ports {FMC2_LPC_LA_P[7]}]
set_property PACKAGE_PIN AL12 [get_ports {FMC2_LPC_LA_N[7]}]
set_property PACKAGE_PIN AM11 [get_ports {FMC2_LPC_LA_P[8]}]
set_property PACKAGE_PIN AN11 [get_ports {FMC2_LPC_LA_N[8]}]
set_property PACKAGE_PIN AH9 [get_ports {FMC2_LPC_LA_P[9]}]
set_property PACKAGE_PIN AH8 [get_ports {FMC2_LPC_LA_N[9]}]
set_property PACKAGE_PIN AE8 [get_ports {FMC2_LPC_LA_P[10]}]
set_property PACKAGE_PIN AF8 [get_ports {FMC2_LPC_LA_N[10]}]
set_property PACKAGE_PIN AE12 [get_ports {FMC2_LPC_LA_P[11]}]
set_property PACKAGE_PIN AF12 [get_ports {FMC2_LPC_LA_N[11]}]
set_property PACKAGE_PIN AH13 [get_ports {FMC2_LPC_LA_P[12]}]
set_property PACKAGE_PIN AJ13 [get_ports {FMC2_LPC_LA_N[12]}]
set_property PACKAGE_PIN AD10 [get_ports {FMC2_LPC_LA_P[13]}]
set_property PACKAGE_PIN AE10 [get_ports {FMC2_LPC_LA_N[13]}]
set_property PACKAGE_PIN AD9 [get_ports {FMC2_LPC_LA_P[14]}]
set_property PACKAGE_PIN AD8 [get_ports {FMC2_LPC_LA_N[14]}]
set_property PACKAGE_PIN AD11 [get_ports {FMC2_LPC_LA_P[15]}]
set_property PACKAGE_PIN AE11 [get_ports {FMC2_LPC_LA_N[15]}]
set_property PACKAGE_PIN AE13 [get_ports {FMC2_LPC_LA_P[16]}]
set_property PACKAGE_PIN AF13 [get_ports {FMC2_LPC_LA_N[16]}]
set_property PACKAGE_PIN N24 [get_ports {FMC2_LPC_LA_P[17]}]
set_property PACKAGE_PIN M24 [get_ports {FMC2_LPC_LA_N[17]}]
set_property PACKAGE_PIN M25 [get_ports {FMC2_LPC_LA_P[18]}]
set_property PACKAGE_PIN M26 [get_ports {FMC2_LPC_LA_N[18]}]
set_property PACKAGE_PIN T24 [get_ports {FMC2_LPC_LA_P[19]}]
set_property PACKAGE_PIN T25 [get_ports {FMC2_LPC_LA_N[19]}]
set_property PACKAGE_PIN T27 [get_ports {FMC2_LPC_LA_P[20]}]
set_property PACKAGE_PIN R27 [get_ports {FMC2_LPC_LA_N[20]}]
set_property PACKAGE_PIN R25 [get_ports {FMC2_LPC_LA_P[21]}]
set_property PACKAGE_PIN R26 [get_ports {FMC2_LPC_LA_N[21]}]
set_property PACKAGE_PIN P26 [get_ports {FMC2_LPC_LA_P[22]}]
set_property PACKAGE_PIN N26 [get_ports {FMC2_LPC_LA_N[22]}]
set_property PACKAGE_PIN J26 [get_ports {FMC2_LPC_LA_P[23]}]
set_property PACKAGE_PIN H26 [get_ports {FMC2_LPC_LA_N[23]}]
set_property PACKAGE_PIN L23 [get_ports {FMC2_LPC_LA_P[24]}]
set_property PACKAGE_PIN L24 [get_ports {FMC2_LPC_LA_N[24]}]
set_property PACKAGE_PIN M27 [get_ports {FMC2_LPC_LA_P[25]}]
set_property PACKAGE_PIN L27 [get_ports {FMC2_LPC_LA_N[25]}]
set_property PACKAGE_PIN J24 [get_ports {FMC2_LPC_LA_P[26]}]
set_property PACKAGE_PIN J25 [get_ports {FMC2_LPC_LA_N[26]}]
set_property PACKAGE_PIN H27 [get_ports {FMC2_LPC_LA_P[27]}]
set_property PACKAGE_PIN G27 [get_ports {FMC2_LPC_LA_N[27]}]
set_property PACKAGE_PIN R23 [get_ports {FMC2_LPC_LA_P[28]}]
set_property PACKAGE_PIN P23 [get_ports {FMC2_LPC_LA_N[28]}]
set_property PACKAGE_PIN L22 [get_ports {FMC2_LPC_LA_P[29]}]
set_property PACKAGE_PIN K23 [get_ports {FMC2_LPC_LA_N[29]}]
set_property PACKAGE_PIN L25 [get_ports {FMC2_LPC_LA_P[30]}]
set_property PACKAGE_PIN K25 [get_ports {FMC2_LPC_LA_N[30]}]
set_property PACKAGE_PIN N22 [get_ports {FMC2_LPC_LA_P[31]}]
set_property PACKAGE_PIN M22 [get_ports {FMC2_LPC_LA_N[31]}]
set_property PACKAGE_PIN J23 [get_ports {FMC2_LPC_LA_P[32]}]
set_property PACKAGE_PIN H24 [get_ports {FMC2_LPC_LA_N[32]}]
set_property PACKAGE_PIN K26 [get_ports {FMC2_LPC_LA_P[33]}]
set_property PACKAGE_PIN K27 [get_ports {FMC2_LPC_LA_N[33]}]

set_property IOSTANDARD LVCMOS18 [get_ports {FMC*}]

# SMA
set_property PACKAGE_PIN H12 [get_ports {SMA_CLKIN_P} ]
set_property PACKAGE_PIN G12 [get_ports {SMA_CLKIN_N} ]
set_property IOSTANDARD LVCMOS18 [get_ports {SMA_CLK*}]

# PCIE
set_property PACKAGE_PIN AB6 [get_ports {PCIE_REFCLK_P} ]
set_property PACKAGE_PIN AB5 [get_ports {PCIE_REFCLK_P} ]
set_property PACKAGE_PIN K22 [get_ports {PCIE_PERST_B_LS} ]
set_property IOSTANDARD LVCMOS18 [get_ports {PCIE_PERST_B_LS}]

# LED

set_property PACKAGE_PIN D20 [get_ports led_test[0]]
set_property PACKAGE_PIN D21 [get_ports led_test[1]]
set_property PACKAGE_PIN N23 [get_ports led[0]]
set_property PACKAGE_PIN V23 [get_ports led[1]]
set_property PACKAGE_PIN V22 [get_ports led[2]]
set_property PACKAGE_PIN V21 [get_ports led[3]]
set_property IOSTANDARD LVCMOS18 [get_ports led*]

# PL uart
set_property IOSTANDARD LVCMOS18 [get_ports UART_rxd]
set_property PACKAGE_PIN AG32 [get_ports UART_rxd]

set_property IOSTANDARD LVCMOS18 [get_ports UART_txd]
set_property PACKAGE_PIN AG31 [get_ports UART_txd]


# for CXP<->FMC-HPC
### onBOARD CLK ###
#fmc ref_clk
set_property PACKAGE_PIN K6 [get_ports fmc_ref_clk_p]

#LOW SPEED TX
#LA02_N
set_property IOSTANDARD LVCMOS18 [get_ports {fmc_tx[3]}]
set_property PACKAGE_PIN E27 [get_ports {fmc_tx[3]}]
#LA01_P_CC
set_property IOSTANDARD LVCMOS18 [get_ports {fmc_tx[2]}]
set_property PACKAGE_PIN E22 [get_ports {fmc_tx[2]}]
#LA01_N_CC
set_property IOSTANDARD LVCMOS18 [get_ports {fmc_tx[1]}]
set_property PACKAGE_PIN E23 [get_ports {fmc_tx[1]}]
# LA00_P_CC FMC1_LA00_CC_P
set_property IOSTANDARD LVCMOS18 [get_ports {fmc_tx[0]}]
set_property PACKAGE_PIN D24 [get_ports {fmc_tx[0]}]

### PoCXP actve low ###
set_property IOSTANDARD LVCMOS18 [get_ports {pocxp_en_tri_o[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pocxp_en_tri_o[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pocxp_en_tri_o[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pocxp_en_tri_o[0]}]

#FMC_HPC0_LA21_N LA21_N
set_property PACKAGE_PIN B12 [get_ports {pocxp_en_tri_o[0]}]
#FMC_HPC0_LA21_P LA21_P
set_property PACKAGE_PIN C12 [get_ports {pocxp_en_tri_o[1]}]
#LA22_N
set_property PACKAGE_PIN B11 [get_ports {pocxp_en_tri_o[2]}]
#LA22_P
set_property PACKAGE_PIN C11 [get_ports {pocxp_en_tri_o[3]}]
