create_clock -period 5.000 [get_ports sys_clk_p]

make_diff_pair_ports sys_clk_p sys_clk_n
set_property PACKAGE_PIN AJ9 [get_ports sys_clk_p]
set_property PACKAGE_PIN AK9 [get_ports sys_clk_n]
set_property IOSTANDARD LVDS [get_ports sys_clk_p]
set_property IOSTANDARD LVDS [get_ports sys_clk_n]

# keys
set_property PACKAGE_PIN J9 [get_ports {pl_key_n}]
set_property PACKAGE_PIN Y22 [get_ports {ps_key_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {*key_n}]

# FMC-HPC

# PCIE
set_property PACKAGE_PIN AD8 [get_ports {PCIE_REFCLK_P} ]
set_property PACKAGE_PIN AD7 [get_ports {PCIE_REFCLK_P} ]
set_property PACKAGE_PIN AA20 [get_ports {PCIE_PERST_B_LS} ]
set_property IOSTANDARD LVCMOS18 [get_ports {PCIE_PERST_B_LS}]
# 40pin
set_property PACKAGE_PIN  E2  [get_ports {alinx40Pin_N[0]} ]
set_property PACKAGE_PIN  E3  [get_ports {alinx40Pin_P[0]} ]
set_property PACKAGE_PIN  D1  [get_ports {alinx40Pin_N[1]} ]
set_property PACKAGE_PIN  E1  [get_ports {alinx40Pin_P[1]} ]
set_property PACKAGE_PIN  C2  [get_ports {alinx40Pin_N[2]} ]
set_property PACKAGE_PIN  D2  [get_ports {alinx40Pin_P[2]} ]
set_property PACKAGE_PIN  G7  [get_ports {alinx40Pin_N[3]} ]
set_property PACKAGE_PIN  H7  [get_ports {alinx40Pin_P[3]} ]
set_property PACKAGE_PIN  D5  [get_ports {alinx40Pin_N[4]} ]
set_property PACKAGE_PIN  D6  [get_ports {alinx40Pin_P[4]} ]
set_property PACKAGE_PIN  F4  [get_ports {alinx40Pin_N[5]} ]
set_property PACKAGE_PIN  F5  [get_ports {alinx40Pin_P[5]} ]
set_property PACKAGE_PIN  D4  [get_ports {alinx40Pin_N[6]} ]
set_property PACKAGE_PIN  E4  [get_ports {alinx40Pin_P[6]} ]
set_property PACKAGE_PIN  J6  [get_ports {alinx40Pin_N[7]} ]
set_property PACKAGE_PIN  J7  [get_ports {alinx40Pin_P[7]} ]
set_property PACKAGE_PIN  B4  [get_ports {alinx40Pin_N[8]} ]
set_property PACKAGE_PIN  C4  [get_ports {alinx40Pin_P[8]} ]
set_property PACKAGE_PIN  B1  [get_ports {alinx40Pin_N[9]} ]
set_property PACKAGE_PIN  C1  [get_ports {alinx40Pin_P[9]} ]
set_property PACKAGE_PIN  A2  [get_ports {alinx40Pin_N[10]} ]
set_property PACKAGE_PIN  A3  [get_ports {alinx40Pin_P[10]} ]
set_property PACKAGE_PIN  B3  [get_ports {alinx40Pin_N[11]} ]
set_property PACKAGE_PIN  C3  [get_ports {alinx40Pin_P[11]} ]
set_property PACKAGE_PIN  A5  [get_ports {alinx40Pin_N[12]} ]
set_property PACKAGE_PIN  B5  [get_ports {alinx40Pin_P[12]} ]
set_property PACKAGE_PIN  E5  [get_ports {alinx40Pin_N[13]} ]
set_property PACKAGE_PIN  F6  [get_ports {alinx40Pin_P[13]} ]
set_property PACKAGE_PIN  G6  [get_ports {alinx40Pin_N[14]} ]
set_property PACKAGE_PIN  H6  [get_ports {alinx40Pin_P[14]} ]
set_property PACKAGE_PIN  G8  [get_ports {alinx40Pin_N[15]} ]
set_property PACKAGE_PIN  H8  [get_ports {alinx40Pin_P[15]} ]
set_property PACKAGE_PIN  M12 [get_ports {alinx40Pin_N[16]} ]
set_property PACKAGE_PIN  N13 [get_ports {alinx40Pin_P[16]} ]

set_property IOSTANDARD LVCMOS18 [get_ports {alinx40Pin*}]

set_property PACKAGE_PIN AN5 [get_ports {PCIE_TX_N[0]}]
set_property PACKAGE_PIN AN6 [get_ports {PCIE_TX_P[0]}]
set_property PACKAGE_PIN AM3 [get_ports {PCIE_TX_N[1]}]
set_property PACKAGE_PIN AM4 [get_ports {PCIE_TX_P[1]}]
set_property PACKAGE_PIN AL5 [get_ports {PCIE_TX_N[2]}]
set_property PACKAGE_PIN AL6 [get_ports {PCIE_TX_P[2]}]
set_property PACKAGE_PIN AJ5 [get_ports {PCIE_TX_N[3]}]
set_property PACKAGE_PIN AJ6 [get_ports {PCIE_TX_P[3]}]

set_property PACKAGE_PIN AP3 [get_ports {PCIE_RX_N[0]}]
set_property PACKAGE_PIN AP4 [get_ports {PCIE_RX_P[0]}]
set_property PACKAGE_PIN AN1 [get_ports {PCIE_RX_N[0]}]
set_property PACKAGE_PIN AN2 [get_ports {PCIE_RX_P[0]}]
set_property PACKAGE_PIN AL1 [get_ports {PCIE_RX_N[0]}]
set_property PACKAGE_PIN AL2 [get_ports {PCIE_RX_P[0]}]
set_property PACKAGE_PIN AK3 [get_ports {PCIE_RX_N[0]}]
set_property PACKAGE_PIN AK4 [get_ports {PCIE_RX_P[0]}]
