name: CRON
on:
  push:
    branches: [master]
  # CRON runs daily
  schedule: [cron: "0 8 * * *"]

jobs:
  cron-check:
    name: CRON Build and Simulate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: build and simulate
        run : |
          sudo apt-get update
          ./setup.sh
          ./run.sh
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
